name: Build Beta

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - reopened

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'beta')
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BRANCH: "${{ github.head_ref }}"
      PR_NUMBER: "${{ github.event.pull_request.number }}"
      PR_TITLE: "${{ github.event.pull_request.title }}"

    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITLANG_AUTH }}

    - name: Date
      id: date
      run: |
        echo "::set-output name=date::$(TZ=":US/Mountain" date +%m/%d/%y_%H:%M:%S)"

    - name: Beta Files
      run : |
        CURRENT_DATE=${{ steps.date.outputs.date }}
        rm -rf docs/index.html docs/404.html docs/CNAME .github README.md
        mkdir .github .github/workflows
        mv beta/workflows/beta-prod.yml beta/workflows/beta-deploy.yml .github/workflows/
        mv beta/index.html beta/404.html beta/CNAME docs/
        mv beta/README.md .
        echo -e "#### Pull Request:\n" >> README.md
        echo -e "### [${PR_TITLE}](https://github.com/chiefmikey/gitlang/pull/${PR_NUMBER})\n" >> README.md
        echo -e "#### Branch:\n" >> README.md
        echo -e "### [${BRANCH}](https://github.com/chiefmikey/gitlang/tree/${BRANCH})\n" >> README.md
        echo -e "#### Date:\n" >> README.md
        echo -e "### ${CURRENT_DATE%%_*}\n" >> README.md
        echo -e "#### Time (MT):\n" >> README.md
        echo -e "### ${CURRENT_DATE##*_}\n" >> README.md
        echo -e "</div>\n" >> README.md
        git config user.name "chiefmikey"
        git config user.email "wolfemikl@gmail.com"
        git add .
        git commit -am "Beta README.md"

    - name: Push Main
      run: |
        CURRENT_DATE=${{ steps.date.outputs.date }}
        git remote set-url --add --push origin https://github.com/chiefmikey/gitlang-beta.git
        git reset $(git commit-tree HEAD^{tree} -m "PR: ${PR_TITLE} | Branch: ${BRANCH} | Date: ${CURRENT_DATE%%_*} | Time: ${CURRENT_DATE##*_}")
        git push -fu origin HEAD:main
        echo "PR: ${PR_TITLE}"
        echo "Branch: ${BRANCH}"
        echo "Date: ${CURRENT_DATE%%_*}"
        echo "Time: ${CURRENT_DATE##*_}"
        echo "https://beta.gitlang.net"
