name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Analyze
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=chiefmikey_gitlang
            -Dsonar.organization=chiefmikey
