name: SonarCloud Analysis

on:
  push:
  pull_request:

permissions:
  pull-requests: read

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze        
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:             
            -Dsonar.projectKey=chiefmikey_gitlang
            -Dsonar.organization=chiefmikey
